GET http://localhost:3000

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/10

###
POST  http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100
}

####
PATCH  http://localhost:3000/products/1
Content-Type: application/json

{
    "name":"Produto Alterado",
    "price": 50 
}

###
DELETE  http://localhost:3000/products/1
Content-Type: application/json